apiVersion: v2
name: aws-monitor-flask
description: Helm chart for the AWS monitoring Flask application
type: application
version: 0.1.0          # chart version
appVersion: "1.0.0"     # application version (can match your image tag)
